# Generated by Django 5.2 on 2025-05-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Cliente', max_length=100)),
                ('apellido', models.CharField(default='Apellido', max_length=100)),
                ('email', models.EmailField(default='cliente@ejemplo.com', max_length=254)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('direccion', models.TextField(default='Sin dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sucursal Principal', max_length=100)),
                ('direccion', models.TextField(default='Por definir')),
                ('ciudad', models.CharField(default='Ciudad desconocida', max_length=50)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('email', models.EmailField(default='sucursal@ejemplo.com', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Escritorio ejecutivo', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=899.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Alejandro', max_length=100)),
                ('apellido', models.CharField(default='Garcia', max_length=100)),
                ('puesto', models.CharField(default='Empleado', max_length=100)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donmueble.sucursal')),
            ],
        ),
    ]
